---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jasonmorsley/ubuntu-with-docker
#    tag: 18.04

inputs:
- name: tested

outputs:
- name: tested

run:
  path: sh
  args:
  - -exec
  - |
    chmod u+x tested/Pipelines/Scripts/containerise.sh
    sh tested/Pipelines/Scripts/containerise.sh